name: llm-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch
      - ollama
      - datasets
      - transformers
      - peft
      - numpy
      - matplotlib
      - gymnasium
      - re
      - time
      - os



